name: AI-toolkit-release-image-generation-workflow

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'The version number of the operator'
          required: true
          default: '0.0.1'

jobs:
  build:
      runs-on: ubuntu-latest
      env:
        IMAGE_TAG_BASE: 'quay.io/openshift-ai-toolkit/openshift-ai-toolkit-operator-test'
      steps: 
        #prerequisite
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Set up Go
          uses: actions/setup-go@v5
        - name: check version 
          run: |
            go env GOARCH
        - name: running make commands
          run: make generate manifests 
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            version: latest      
            platforms: linux/s390x
        - name: Log in to QUAY
          uses: docker/login-action@v2
          with:
             registry: quay.io
             username: ${{ secrets.CR_USER_NAME }}
             password: ${{ secrets.CR_SECRET }}
        #builds
        - name: Docker build and push using dockerbuildx
          run: |
            docker build --platform linux/s390x -t ${{ IMAGE_TAG_BASE }}-controller:v${{ github.event.inputs.VERSION }} .
            make docker-push   
        - name: Bundle build and push
          run: |
            make bundle 
            docker build -f bundle.Dockerfile -t ${{ IMAGE_TAG_BASE }}-bundle:v${{ github.event.inputs.VERSION }} .
            make bundle-push 